---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Github Actions - OIDC Identity Provider"

Parameters:

  ProviderName:
    Type: String
    Description: "Give the IDP a Descriptive Name"
    Default: "GitHub-OIDC-Provider"

Resources:

  IdpGitHubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
      - Key: Name
        Value: !Ref ProviderName

Outputs:

  IdpGitHubOidc:
    Description: "ARN of Github OIDC Provider"
    Value: !GetAtt IdpGitHubOidc.Arn
    Export:
      Name: !Sub ${ProviderName}-Arn