---
name: "Deliver Resources to S3"

on:
  push:
    branches:
      - master
      - main

env:

  ## GLOBAL VARIABLES

  ### Commercial
  COM_NAME: ${{ secrets.COM_AWS_ROLE_SESSION_NAME }}
  COM_DURATION: ${{ secrets.COM_AWS_ROLE_SESSION_DURATION }}
  COM_REGION: ${{ secrets.COM_AWS_DEFAULT_REGION }}
  COM_ROLE: ${{ secrets.COM_ROLE_ARN_DELIVERY }}

  ### GovCloud
  GOV_NAME: ${{ secrets.GOV_AWS_ROLE_SESSION_NAME }}
  GOV_DURATION: ${{ secrets.GOV_AWS_ROLE_SESSION_DURATION }}
  GOV_REGION: ${{ secrets.GOV_AWS_DEFAULT_REGION }}
  GOV_ROLE: ${{ secrets.GOV_ROLE_ARN_DELIVERY }}

  ## PROJECT VARIABLES
  BUCKET: solutions.rwick.it
  PREFIX: github-cicd
  DIRECTORY: cloudformation

jobs:
  Deliver-Commercial:
    name: Commercial - Deliver Resources to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: ${{ env.COM_NAME }}
        role-duration-seconds: ${{ env.COM_DURATION }}
        aws-region: ${{ env.COM_REGION }}
        role-to-assume: ${{ env.COM_ROLE }}

    - name: Sync to S3
      run: |
        aws s3 sync ${{ env.DIRECTORY }} s3://${{ env.BUCKET }}/${{ env.PREFIX }}

  Deliver-GovCloud:
    name: GovCloud - Deliver Resources to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: ${{ env.GOV_NAME }}
        role-duration-seconds: ${{ env.GOV_DURATION }}
        aws-region: ${{ env.GOV_REGION }}
        role-to-assume: ${{ env.GOV_ROLE }}

    - name: Sync to S3
      run: |
        aws s3 sync ${{ env.DIRECTORY }} s3://${{ env.BUCKET }}/${{ env.PREFIX }}