---
name: "Deliver Resources to S3"

on:
  push:
    branches:
      - master
      - main

env:

  ## GLOBAL VARIABLES
  AWS_ROLE_SESSION_NAME: ${{ secrets.ROLE_SESSION_NAME }}
  AWS_ROLE_SESSION_DURATION: ${{ secrets.ROLE_SESSION_DURATION }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  ## PROJECT VARIABLES
  AWS_ROLE_ARN: ${{ secrets.DELIVER_ROLE_ARN }}
  AWS_CFN_BUCKET: solutions.rwick.it
  AWS_BUCKET_PREFIX: github-cicd
  CFN_DIR: cloudformation

jobs:
  Deliver:
    name: Deliver Resources to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-duration-seconds: ${{ env.AWS_ROLE_SESSION_DURATION }}
        role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Sync to S3
      run: |
        aws s3 sync ${{ env.CFN_DIR }} s3://${{ env.AWS_CFN_BUCKET }}/${{ env.AWS_BUCKET_PREFIX }} --region ${{ env.AWS_DEFAULT_REGION }}