---
name: "Deploy Resources"

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - master
  #     - main

env:

  ## GLOBAL VARIABLES

  ### Commercial
  COM_NAME: ${{ secrets.COM_AWS_ROLE_SESSION_NAME }}
  COM_DURATION: ${{ secrets.COM_AWS_ROLE_SESSION_DURATION }}
  COM_REGION: ${{ secrets.COM_AWS_DEFAULT_REGION }}
  COM_ROLE: ${{ secrets.COM_ROLE_ARN_DELIVER }}

  ### GovCloud
  GOV_NAME: ${{ secrets.GOV_AWS_ROLE_SESSION_NAME }}
  GOV_DURATION: ${{ secrets.GOV_AWS_ROLE_SESSION_DURATION }}
  GOV_REGION: ${{ secrets.AWS_GOV_DEFAULT_REGION }}
  GOV_ROLE: ${{ secrets.GOV_ROLE_ARN_DELIVER }}

  ## PROJECT VARIABLES


jobs:
  Deploy-Commercial:
    name: Commercial - Deploy Resources
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: ${{ env.COM_NAME }}
        role-duration-seconds: ${{ env.COM_DURATION }}
        aws-region: ${{ env.COM_REGION }}
        role-to-assume: ${{ env.COM_ROLE }}

    # - name: Deploy/Update Stack
    #     uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
    #     with:
    #       name: bucket-effectual-mcm
    #       template: cloudformation/
    #       no-fail-on-empty-changeset: "1"

  Deploy-GovCloud:
    name: GovCloud - Deploy Resources
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: ${{ env.GOV_NAME }}
        role-duration-seconds: ${{ env.GOV_DURATION }}
        aws-region: ${{ env.GOV_REGION }}
        role-to-assume: ${{ env.GOV_ROLE }}

    # - name: Deploy/Update Stack
    #     uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
    #     with:
    #       name: bucket-effectual-mcm
    #       template: cloudformation/
    #       no-fail-on-empty-changeset: "1"